/**
 * Site-wide constants
 */

export const SITE_CONFIG = {
  name: "Arcade Studios",
  tagline: "Building digital products for next-gen brands",
  description:
    "Arcade Studios builds modern web applications, digital products, and innovative solutions for startups, agencies, and next-gen brands.",
  url: "https://arcadestudios.com",
  email: "kysondana@gmail.com",
  location: "Santa Cruz, CA",
  social: {
    linkedin: "https://linkedin.com/in/kysondana",
    instagram: "https://instagram.com/kysondana",
    youtube: "https://youtube.com/@kysondana",
    github: "https://github.com/kysondana",
    twitter: "https://twitter.com/kysondana",
  },
};

export const NAV_LINKS = [
  {
    label: "Work",
    href: "/work",
  },
  {
    label: "About",
    href: "/about",
  },
  {
    label: "Contact",
    href: "/contact",
  },
];

export const ANIMATION_TIMINGS = {
  heroTyping: {
    wordDelay: 100,
    totalDuration: 2500,
  },
  introCopyDelay: 2500,
  introCopyDuration: 600,
  scrollReveal: {
    twoUp: 200,
    brandShowcase: 300,
    capabilities: 300,
    featuredWork: 200,
    darkroom: 800,
    footer: 400,
  },
  staggerDelay: {
    logos: 100,
    cards: 200,
  },
};

export const BREAKPOINTS = {
  mobile: 768,
  tablet: 1024,
  desktop: 1920,
};

export const SERVICE_CATEGORIES = [
  {
    id: "web-development",
    title: "Web Development",
    description: "Custom websites and web applications built with modern technologies",
    icon: "🌐",
    works: [
      {
        id: "rivian-website",
        title: "Electric Adventures Platform",
        description: "Full-stack web application for electric vehicle owners to discover and share adventure routes",
        client: "Rivian",
        category: "web-development",
        tags: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
        image: "https://images.unsplash.com/photo-1617886322207-5baae5fc7c5a?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "tesla-configurator",
        title: "Vehicle Configurator",
        description: "Interactive 3D vehicle customization platform with real-time pricing and availability",
        client: "Tesla",
        category: "web-development",
        tags: ["React", "Three.js", "WebGL", "Node.js"],
        image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "solar-dashboard",
        title: "Energy Management Dashboard",
        description: "Real-time solar energy monitoring and analytics platform for homeowners",
        client: "SolarCity",
        category: "web-development",
        tags: ["Vue.js", "D3.js", "Python", "FastAPI"],
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
      {
        id: "outdoor-ecommerce",
        title: "Adventure Gear Marketplace",
        description: "E-commerce platform with advanced filtering and personalized recommendations",
        client: "Black Diamond",
        category: "web-development",
        tags: ["Shopify", "React", "GraphQL", "Stripe"],
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
    ],
  },
  {
    id: "mobile-apps",
    title: "Mobile Apps",
    description: "Native and cross-platform mobile applications for iOS and Android",
    icon: "📱",
    works: [
      {
        id: "fitness-tracker",
        title: "AI Fitness Companion",
        description: "Personalized workout tracking app with AI-powered form correction and progress analytics",
        client: "FitTech",
        category: "mobile-apps",
        tags: ["React Native", "TensorFlow", "Firebase", "AWS"],
        image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "food-delivery",
        title: "Local Food Delivery Network",
        description: "Sustainable food delivery platform connecting local restaurants with conscious consumers",
        client: "GreenEats",
        category: "mobile-apps",
        tags: ["Flutter", "Dart", "Google Maps", "Stripe"],
        image: "https://images.unsplash.com/photo-1526367790999-0150786686a2?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "meditation-app",
        title: "Mindfulness & Meditation",
        description: "Premium meditation app with personalized programs and sleep soundscapes",
        client: "MindSpace",
        category: "mobile-apps",
        tags: ["Swift", "SwiftUI", "CoreML", "HealthKit"],
        image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
      {
        id: "travel-planner",
        title: "Smart Travel Companion",
        description: "AI-powered travel planning app with real-time itinerary optimization",
        client: "Wanderlust",
        category: "mobile-apps",
        tags: ["Kotlin", "Jetpack Compose", "Google AI", "Maps SDK"],
        image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
    ],
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    description: "Data-driven marketing campaigns and SEO strategies that drive growth",
    icon: "📈",
    works: [
      {
        id: "saas-growth",
        title: "SaaS Growth Campaign",
        description: "360° digital marketing strategy that achieved 300% MRR growth in 6 months",
        client: "CloudSync",
        category: "digital-marketing",
        tags: ["SEO", "Content Marketing", "PPC", "Analytics"],
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "ecommerce-boost",
        title: "E-commerce SEO Transformation",
        description: "Complete SEO overhaul resulting in 250% organic traffic increase and 180% revenue growth",
        client: "StyleHub",
        category: "digital-marketing",
        tags: ["Technical SEO", "Link Building", "Content Strategy"],
        image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "social-media-campaign",
        title: "Viral Social Media Campaign",
        description: "Multi-platform social media strategy generating 50M+ impressions and 2M+ engagements",
        client: "EcoBottle",
        category: "digital-marketing",
        tags: ["Social Media", "Influencer Marketing", "Video Content"],
        image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
      {
        id: "content-marketing",
        title: "B2B Content Hub",
        description: "Thought leadership content platform establishing brand as industry authority",
        client: "DataVault",
        category: "digital-marketing",
        tags: ["Content Strategy", "Whitepapers", "Webinars", "Lead Gen"],
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
    ],
  },
  {
    id: "branding",
    title: "Branding & Identity",
    description: "Comprehensive brand strategies and visual identities that stand out",
    icon: "🎨",
    works: [
      {
        id: "startup-rebrand",
        title: "Startup Brand Identity",
        description: "Complete brand identity system for innovative fintech startup",
        client: "PayFlow",
        category: "branding",
        tags: ["Brand Strategy", "Logo Design", "Brand Guidelines", "Typography"],
        image: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "restaurant-brand",
        title: "Restaurant Rebranding",
        description: "Modern brand refresh for upscale dining establishment including packaging and collateral",
        client: "Harvest & Vine",
        category: "branding",
        tags: ["Rebranding", "Packaging", "Print Design", "Photography"],
        image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "sustainable-brand",
        title: "Sustainable Fashion Brand",
        description: "Eco-conscious brand identity for ethical clothing company",
        client: "Thread Collective",
        category: "branding",
        tags: ["Brand Identity", "Sustainable Design", "Digital Assets"],
        image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
      {
        id: "tech-brand",
        title: "Tech Startup Visual Identity",
        description: "Bold and modern brand identity for AI-powered productivity tool",
        client: "FlowState",
        category: "branding",
        tags: ["Visual Identity", "Motion Graphics", "Brand Story"],
        image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
    ],
  },
  {
    id: "ecommerce",
    title: "E-commerce Solutions",
    description: "End-to-end e-commerce platforms that convert visitors into customers",
    icon: "🛍️",
    works: [
      {
        id: "fashion-store",
        title: "Luxury Fashion Boutique",
        description: "High-end e-commerce platform with custom checkout experience and AR try-on",
        client: "Noir & Blanc",
        category: "ecommerce",
        tags: ["Shopify Plus", "AR Integration", "Custom Theme", "Klaviyo"],
        image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "subscription-box",
        title: "Subscription Box Platform",
        description: "Custom subscription management system with personalized product recommendations",
        client: "The Curated Box",
        category: "ecommerce",
        tags: ["WooCommerce", "Subscriptions", "WordPress", "Payment Gateway"],
        image: "https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=1600&h=900&fit=crop&q=80",
        year: "2024",
      },
      {
        id: "electronics-store",
        title: "Electronics Marketplace",
        description: "Multi-vendor marketplace with advanced filtering and comparison tools",
        client: "TechMart",
        category: "ecommerce",
        tags: ["Magento", "Multi-vendor", "Advanced Search", "Reviews"],
        image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
      {
        id: "handmade-marketplace",
        title: "Artisan Marketplace",
        description: "Community-driven platform connecting artisans with conscious consumers",
        client: "Crafted Goods",
        category: "ecommerce",
        tags: ["Custom Platform", "React", "Stripe Connect", "Community"],
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a91?w=1600&h=900&fit=crop&q=80",
        year: "2023",
      },
    ],
  },
];
